// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1TTYhQU3q0_gjwp6cY2jdt6YBEVc9Tf4',
    appId: '1:2578149983:web:e89046315a1c96e9f861ea',
    messagingSenderId: '2578149983',
    projectId: 'jokes-app-52e78',
    authDomain: 'jokes-app-52e78.firebaseapp.com',
    storageBucket: 'jokes-app-52e78.firebasestorage.app',
    measurementId: 'G-YFG9NSJQ6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0v_HlRX18tVRjwDLETqNnlIixDyy-wq0',
    appId: '1:2578149983:android:bb678f8511e0ff63f861ea',
    messagingSenderId: '2578149983',
    projectId: 'jokes-app-52e78',
    storageBucket: 'jokes-app-52e78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVpf-t6csdQO2c9o8v0RxqETVDWzTN26w',
    appId: '1:2578149983:ios:95182ec0305b483bf861ea',
    messagingSenderId: '2578149983',
    projectId: 'jokes-app-52e78',
    storageBucket: 'jokes-app-52e78.firebasestorage.app',
    iosBundleId: 'mk.ukim.finki.misLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVpf-t6csdQO2c9o8v0RxqETVDWzTN26w',
    appId: '1:2578149983:ios:95182ec0305b483bf861ea',
    messagingSenderId: '2578149983',
    projectId: 'jokes-app-52e78',
    storageBucket: 'jokes-app-52e78.firebasestorage.app',
    iosBundleId: 'mk.ukim.finki.misLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1TTYhQU3q0_gjwp6cY2jdt6YBEVc9Tf4',
    appId: '1:2578149983:web:5e511ad330d242aef861ea',
    messagingSenderId: '2578149983',
    projectId: 'jokes-app-52e78',
    authDomain: 'jokes-app-52e78.firebaseapp.com',
    storageBucket: 'jokes-app-52e78.firebasestorage.app',
    measurementId: 'G-02BHML51YC',
  );
}
